language: node_js
os: linux
dist: xenial
node_js:
  - 12
script:
  - npm install
  - npm run build
  - tar -C pkg -czvf package.tar.gz .
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: "package.tar.gz"
  cleanup: true
  draft: true
  on:
    tags: true