language: node_js
os: linux
dist: xenial
node_js:
  - 12
script:
  - npm install
  - npm run build
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: pkg/*
  cleanup: false
  draft: true
  on:
    tags: true