language: node_js
os: linux
dist: xenial
node_js:
  - 14
jobs:
  include:
    - stage: test
      script:
        - npm run test
        - npm run coverage
        - npm run report-coverage
    - stage: build
      script:
        - npm run build
        - tar -C pkg -czvf package.tar.gz .
install:
  - npm ci
cache:
  directories:
    - $HOME/.npm
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  skip_cleanup: true
  file: package.tar.gz
  draft: true
  'on':
    tags: true
