language: node_js
os: linux
dist: xenial
node_js:
  - 12
script:
  - npm install
  - npm run build
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  cleanup: true
  draft: true
  on:
    tags: true